name: SonarQube Scan

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      student_repo:
        description: 'Student Repository (e.g. org/repo)'
        required: false
        type: string

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:

      # ---------------------------
      # Checkout Code
      # ---------------------------
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.student_repo || github.repository }}

      # ---------------------------
      # Setup Java (Required)
      # ---------------------------
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # ---------------------------
      # Setup Python
      # ---------------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # ---------------------------
      # Install Dependencies
      # ---------------------------
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # ---------------------------
      # Fix Import Path (IMPORTANT)
      # ---------------------------
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      # ---------------------------
      # Run Tests with Coverage
      # ---------------------------
      - name: Run tests
        run: |
          pytest tests/ --cov=. --cov-report=xml

      # ---------------------------
      # Verify Coverage File
      # ---------------------------
      - name: Check coverage
        run: |
          ls -l coverage.xml

      # ---------------------------
      # Determine Project Key
      # ---------------------------
      - name: Determine Project Key
        run: |
          if [ -n "${{ inputs.student_repo }}" ]; then
            REPO_CLEAN=$(echo "${{ inputs.student_repo }}" | tr '/' '-')
            echo "PROJECT_KEY=${{ github.repository_owner }}_${REPO_CLEAN}" >> $GITHUB_ENV
          else
            echo "PROJECT_KEY=${{ github.repository_owner }}_${{ github.event.repository.name }}" >> $GITHUB_ENV
          fi

      # ---------------------------
      # SonarQube Scan
      # ---------------------------
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_HOST_URL: http://187.127.142.34:9000/
        with:
          args: >
            -Dsonar.projectKey=${{ env.PROJECT_KEY }}
            -Dsonar.sources=.
            -Dsonar.login=squ_e1ef3d2c794145aeccbf80b96433e4f8957aba08
            -Dsonar.python.coverage.reportPaths=coverage.xml
